name: Jossentials
version: '${version}'
main: gg.jos.jossentials.Jossentials
api-version: '1.21'
authors: [ JosTheDude ]
description:  A modular, configurable, and extremely intuitive all-in-one command core for awesome servers.
website: https://jos.gg/

commands:
  homes:
    description: Open the homes GUI.
    usage: /homes
  spawn:
    description: Teleport to spawn.
    usage: /spawn
  setspawn:
    description: Set the server spawn.
    usage: /setspawn
  tpa:
    description: Request to teleport to another player.
    usage: /tpa <player>
    aliases: [tpask]
  tpahere:
    description: Request a player to teleport to you.
    usage: /tpahere <player>
  tpaccept:
    description: Accept a teleport request.
    usage: /tpaccept [player]
    aliases: [tpyes]
  tpdeny:
    description: Deny a teleport request.
    usage: /tpdeny [player]
    aliases: [tpno]
  tpcancel:
    description: Cancel your outgoing teleport request.
    usage: /tpcancel
  jossentials:
    description: Jossentials main command.
    usage: /jossentials reload
    aliases: [joss, jessentials]

permissions:
  jossentials.homes.1:
    description: Access to home slot 1.
    default: true
  jossentials.homes.2:
    description: Access to home slot 2.
    default: false
  jossentials.homes.3:
    description: Access to home slot 3.
    default: false
  jossentials.homes.4:
    description: Access to home slot 4.
    default: false
  jossentials.homes.5:
    description: Access to home slot 5.
    default: false
  jossentials.homes.teleport.bypass:
    description: Bypass homes teleport warmup/cancel checks.
    default: op
  jossentials.tpa:
    description: Request teleport to a player.
    default: true
  jossentials.tpa.here:
    description: Request a player to teleport to you.
    default: true
  jossentials.tpa.accept:
    description: Accept teleport requests.
    default: true
  jossentials.tpa.deny:
    description: Deny teleport requests.
    default: true
  jossentials.tpa.cancel:
    description: Cancel teleport requests.
    default: true
  jossentials.tpa.teleport.bypass:
    description: Bypass tpa teleport warmup/cancel checks.
    default: op
  jossentials.spawn:
    description: Teleport to spawn.
    default: true
  jossentials.setspawn:
    description: Set the server spawn.
    default: op
  jossentials.spawn.teleport.bypass:
    description: Bypass spawn teleport warmup/cancel checks.
    default: op
  jossentials.workbench.crafting_table:
    description: Open the crafting table workbench.
    default: true
  jossentials.workbench.anvil:
    description: Open the anvil workbench.
    default: true
  jossentials.workbench.cartography_table:
    description: Open the cartography table workbench.
    default: true
  jossentials.workbench.grindstone:
    description: Open the grindstone workbench.
    default: true
  jossentials.workbench.loom:
    description: Open the loom workbench.
    default: true
  jossentials.workbench.smithing_table:
    description: Open the smithing table workbench.
    default: true
  jossentials.workbench.stonecutter:
    description: Open the stonecutter workbench.
    default: true
  jossentials.workbench.enchanting_table:
    description: Open the enchanting table workbench.
    default: true
  jossentials.workbench.brewing_stand:
    description: Open the brewing stand workbench.
    default: true
  jossentials.workbench.furnace:
    description: Open the furnace workbench.
    default: true
  jossentials.workbench.blast_furnace:
    description: Open the blast furnace workbench.
    default: true
  jossentials.workbench.smoker:
    description: Open the smoker workbench.
    default: true
  jossentials.reload:
    description: Reload Jossentials configuration.
    default: op

libraries:
  - org.xerial:sqlite-jdbc:3.51.1.0
  - com.mysql:mysql-connector-j:9.6.0
